version: '3.9'

services:
  databaseToken:
    image: postgres
    container_name: database_token_agenda

    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=token
      - POSTGRES_PASSWORD=tokenlab
      - POSTGRES_DB=agendatoken
    volumes:
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: agendatoken
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - databaseToken
    depends_on:
      - databaseToken

volumes:
  pgdata:
    driver: local
    